appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
hiera.yaml:
  delete: true
data/common.yaml:
  delete: true
CHANGELOG.md:
  delete: true
.travis.yml:
  extras:
    -
      env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec
      rvm: 2.1.9
      stage: spec
